const themes = [
  {
    name: 'blue',
    // firstTime: true,
    colorPrimary: '#4ea9da',
    colorAlternate: '#FAFAFA',
    textHighlight: '#daedf7',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'snowy-black',
    firstTime: true,
    colorPrimary: '#303030',
    colorAlternate: '#F2FAFA',
    textHighlight: '#B8CCCC',
    textPrimary: '#202121',
    navColor: 'rgba(246, 250, 254, 0.75)',
  },
  {
    name: 'turquoise',
    //firstTime: true,
    colorPrimary: '#3dc0b0',
    colorAlternate: '#FAFAFA',
    textHighlight: '#d7f2ef',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'blue-alt',
    colorPrimary: '#FAFAFA',
    colorAlternate: '#4ea9da',
    textHighlight: '#2a93cb',
    textPrimary: '#FAFAFA',
    navColor: 'rgba(78, 169, 218, 0.75)',
  },
  {
    name: 'turquoise-alt',
    colorPrimary: '#FAFAFA',
    colorAlternate: '#3dc0b0',
    textHighlight: '#35a698',
    textPrimary: '#FAFAFA',
    navColor: 'rgba(61, 192, 176, 0.75)',
  },
  {
    name: 'green',
    colorPrimary: '#5BA150',
    colorAlternate: '#FAFAFA',
    textHighlight: '#e1efdf',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'brown',
    colorPrimary: '#A26836',
    colorAlternate: '#FAFAFA',
    textHighlight: '#f5ebe2',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'orange',
    colorPrimary: '#e17421',
    colorAlternate: '#FAFAFA',
    textHighlight: '#f9e4d5',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'crimson-red',
    colorPrimary: '#e64f52',
    colorAlternate: '#FAFAFA',
    textHighlight: '#fbe4e4',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'red',
    colorPrimary: '#af3d4e',
    colorAlternate: '#FAFAFA',
    textHighlight: '#f6e4e7',
    textPrimary: '#202121',
    navColor: 'rgba(250, 250, 250, 0.75)',
  },
  {
    name: 'red-alt',
    colorPrimary: '#FFFFFF',
    colorAlternate: '#89303d',
    textHighlight: '#63232c',
    textPrimary: '#FFFFFF',
    navColor: 'rgba(137, 48, 61, 0.75)',
  },
  {
    name: 'indigo-alt',
    colorPrimary: '#FAFAFA',
    colorAlternate: '#303F9F',
    textHighlight: '#242f78',
    textPrimary: '#FAFAFA',
    navColor: 'rgba(48, 63, 159, 0.75)',
  },
  {
    name: 'grey-alt',
    colorPrimary: '#FFFFFF',
    colorAlternate: '#485564',
    textHighlight: '#333c46',
    textPrimary: '#FFFFFF',
    navColor: 'rgba(72, 85, 100, 0.75)',
  },
  {
    name: 'material-cyan',
    colorPrimary: '#00BCD4',
    colorAlternate: '#FFFFFF',
    textHighlight: '#d4faff',
    textPrimary: '#212121',
    navColor: 'rgba(255, 255, 255, 0.75)',
  },
  {
    name: 'material-brown',
    colorPrimary: '#845c4e',
    colorAlternate: '#FFFFFF',
    textHighlight: '#eee6e3',
    textPrimary: '#212121',
    navColor: 'rgba(255, 255, 255, 0.75)',
  },
  {
    name: 'material-grey',
    colorPrimary: '#607D8B',
    colorAlternate: '#FFFFFF',
    textHighlight: '#dfe6e9',
    textPrimary: '#212121',
    navColor: 'rgba(255, 255, 255, 0.75)',
  },
  {
    name: 'material-grey-alt',
    //firstTime: true,
    colorPrimary: '#FFFFFF',
    colorAlternate: '#455A64',
    textHighlight: '#374850',
    textPrimary: '#FAFAFA',
    navColor: 'rgba(69, 90, 100, 0.75)',
  },
];

export const getThemes = () => {
  return themes.map((theme) => {
    return {
      name: theme.name,
      firstTime: theme.firstTime,
      colorPrimary: theme.colorPrimary,
      colorAlternate: theme.colorAlternate,
      textHighlight: theme.textHighlight,
      bgPrimary: theme.colorAlternate,
      bgAlternate: theme.colorPrimary,
      bgLanding: theme.colorPrimary,
      textPrimary: theme.textPrimary,
      textAlternate: theme.colorAlternate,
      textLanding: theme.colorPrimary,
      parallaxStars: theme.colorPrimary,
      navColor: theme.navColor,
    };
  });
};
